apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: poc
  namespace: argocd
spec:
  description: PoC service

  # only this repo
  sourceRepos:
    - https://github.com/vedantpanwar-styli/styli-poc-gitops

  # only these namespaces
  destinations:
    - server: https://kubernetes.default.svc
      namespace: poc-service-dev
    - server: https://kubernetes.default.svc
      namespace: poc-service-qa
    - server: https://kubernetes.default.svc
      namespace: poc-service-uat
    - server: https://kubernetes.default.svc
      namespace: poc-service-prod

  # nothing cluster-scoped
  clusterResourceWhitelist: []
