apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: poc-dev
  namespace: argocd
spec:
  goTemplate: false
  generators:
    - git:
        repoURL: https://github.com/vedantpanwar-styli/styli-poc-gitops
        revision: main
        files:
          - path: "envs/dev/apps/*.yaml"

  template:
    metadata:
      name: "dev-{{service}}"
    spec:
      project: poc
      sources:
        - repoURL: https://github.com/vedantpanwar-styli/styli-poc-gitops
          targetRevision: main
          path: charts/poc-service
          helm:
            valueFiles:
              - $values/envs/dev/apps/{{service}}.yaml
        - repoURL: https://github.com/vedantpanwar-styli/styli-poc-gitops
          targetRevision: main
          ref: values
      destination:
        name: "{{cluster}}"
        namespace: poc-service-dev
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions: [CreateNamespace=true]
