apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: poc-prod
  namespace: argocd
spec:
  goTemplate: false

  # a bad edit here must never delete running production workloads
  syncPolicy:
    preserveResourcesOnDeletion: true

  generators:
    - git:
        repoURL: https://github.com/vedantpanwar-styli/styli-poc-gitops
        revision: main
        files:
          - path: "envs/prod/apps/*.yaml"

  template:
    metadata:
      name: "prod-{{service}}"
    spec:
      project: poc
      sources:
        - repoURL: https://github.com/vedantpanwar-styli/styli-poc-gitops
          targetRevision: main
          path: charts/poc-service
          helm:
            valueFiles:
              - $values/envs/prod/apps/{{service}}.yaml
        - repoURL: https://github.com/vedantpanwar-styli/styli-poc-gitops
          targetRevision: main
          ref: values
      destination:
        name: "{{cluster}}"
        namespace: poc-service-prod
      syncPolicy:
        # no automated block
        syncOptions: [CreateNamespace=true]
